spring:
    datasource:
        url: jdbc:h2:file:C:/Users/fmint/projects/data/workout-tracker
        driverClassName: org.h2.Driver
        username: admin
        password: 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true